spring.application.name=microservice
spring.data.mongodb.uri=mongodb+srv://bejawadarajkumar282:bunny282@cluster0.okbkntf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=chatdb
server.port=8086
jwt.secret=dlkkdnlnvaionvajfvnajfkanbhfbvarbvjafav
spring.devtools.restart.enabled=true
logging.level.org.springframework=INFO
logging.level.com.chat=DEBUG